CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGINT NOT NULL PRIMARY KEY,
  hash VARCHAR(128) NOT NULL UNIQUE,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  thumbnail VARCHAR(512) NULL,
  sticky BOOLEAN NOT NULL,
  private BOOLEAN NOT NULL,
  created TIMESTAMPTZ NOT NULL,
  updated TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT NOT NULL PRIMARY KEY,
  tag VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS bookmarks_tags (
  bookmark_id BIGINT NOT NULL REFERENCES bookmarks(id),
  tag_id BIGINT NOT NULL REFERENCES tags(id),
  PRIMARY KEY (bookmark_id, tag_id)
);
