CREATE TABLE IF NOT EXISTS bookmarks (
  id BIGINT NOT NULL PRIMARY KEY,
  short_url VARCHAR(256) NOT NULL UNIQUE,
  url TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  thumbnail TEXT NULL,
  sticky BOOLEAN NOT NULL,
  private BOOLEAN NOT NULL,
  -- created DATETIME NOT NULL,
  -- updated DATETIME NOT NULL,
  created TIMESTAMP WITH TIMEZONE NOT NULL,
  updated TIMESTAMP WITH TIMEZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id BIGINT NOT NULL PRIMARY KEY,
  tag VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXIST bookmarks_tags (
  bookmark_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  PRIMARY KEY (bookmark_id, tag_id)
);
